name: refresh
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make sure folders exist
        run: |
          mkdir -p data_clean
          mkdir -p data_raw

      - name: Write a test file
        run: |
          echo "smoke-test: $(date -u)" > data_clean/_smoke.txt

      - name: Commit artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data_clean/_smoke.txt
          git commit -m "Smoke test: write file" || echo "No changes to commit"
          git push
